spring:
    application:
        name: LightJason - Example Miner

    session:
        store-type: redis
        redis:
            flush-mode=on-save: on-save
            namespace: spring:session

    redis:
        host: ${HOST}
        port: ${PORT}
        password: ${PASSWORD}

server:
    servlet:
        session:
            timeout: ${SESSIONTIMEOUT}
